### ISSUE TITLE
【依頼】フリマアプリ挙動確認	

### ISSUE THREAD

**Issue by lynxlevin** [lynxlevin/furima-31051#10]
# URL
https://furima-31051.herokuapp.com/
# Basic認証 ID パスワード
ID:admin
pass:2222
# 出品者
ID:lynx.levin88@gmail.com
pass:111aaa
# 購入者
ID:masahiro.yamamoto0403@gmail.com
pass:111aaa
# Pay.jp テストカード
番号：4242424242424242
期限：12月/24年
セキュリティコード：123

**Comment by airraid714** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
